server:
  port: 8080
spring:
  elasticsearch:
    rest:
      uris: 
  jackson:
    property-naming-strategy: SNAKE_CASE
    date-format: yyyy-MM-dd HH:mm:ss
    locale: zh
    time-zone: GMT+8
    default-property-inclusion: NON_NULL
    serialization:
      fail_on_empty_beans: true # 对象为空时是否报错，默认true
    deserialization:
      fail_on_unknown_properties: false #json中含pojo不存在属性时是否失败报错,默认true

logging:
  level:
    com.bruin.elasticsearch: debug